angular.module("metro2").run(["$templateCache", function($templateCache) {$templateCache.put("components/metro/metro.html","<metro-nav></metro-nav><metro-tab></metro-tab>");
$templateCache.put("components/metro/components/grid/components/metro-grid/metro-grid.html","metro-grid.html");
$templateCache.put("components/metro/components/grid/components/metro-grid-group/metro-grid-group.html","");
$templateCache.put("components/metro/components/grid/components/metro-tile/metro-tile.html","metro-tile.html");
$templateCache.put("components/metro/components/list/components/metro-list/metro-list.html","metro-list.html");
$templateCache.put("components/metro/components/list/components/metro-list-group/metro-list-group.html","metro-list-group.html");
$templateCache.put("components/metro/components/list/components/metro-list-item/metro-list-item.html","");
$templateCache.put("components/metro/components/nav/components/metro-nav/metro-nav.html","<h1>Starta</h1><metro-user></metro-user>");
$templateCache.put("components/metro/components/nav/components/metro-user/metro-user.html","<i class=\"fa fa-google\"></i><h3>Wikipedia</h3><label>De vrije encyclopedie</label>");
$templateCache.put("components/metro/components/searchbox/components/metro-searchbox/metro-searchbox.html","metro-searchbox.html");
$templateCache.put("components/metro/components/tab/components/metro-tab/metro-tab.html","<button ng-click=\"changeView()\">Change View</button><metro-grid ng-if=\"gridview\"></metro-grid><metro-list ng-if=\"!gridview\"></metro-list>");}]);